<?xml version="1.0" encoding="UTF-8"?><definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/Web-Services-hw2-Bank/java/bankWSDL" xmlns:ns="http://bank/" name="bankWSDL" targetNamespace="http://bank/">
<wsdl:import namespace="http://bank/" location="bankWSDL.wsdl"/>
<wsdl:binding name="BankServicesBinding" type="ns:BankServices">
<soap:binding xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" transport="http://schemas.xmlsoap.org/soap/http" style="rpc"/>
<wsdl:operation name="pay">
<soap:operation xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" soapAction="pay_action"/>
<wsdl:input name="input1">
<soap:body xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" namespace="http://bank/" use="literal"/>
</wsdl:input>
<wsdl:output name="output1">
<soap:body xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" namespace="http://bank/" use="literal"/>
</wsdl:output>
</wsdl:operation>
</wsdl:binding>
<wsdl:service name="BankServicesService">
<wsdl:port name="BankServicesPort" binding="ns:BankServicesBinding">
<soap:address xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" location="REPLACE_WITH_ACTUAL_URL"/>
</wsdl:port>
</wsdl:service>
</definitions>
